services:
  - type: worker
    name: school-festival-discord-bot
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_GUILD_ID
        sync: false
      - key: COMMANDS_SCOPE
        value: guild
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: info

